# THE LINEAR CONJUGATE GRADIENT METHON (CGM)

The CGM is an iterative methon for solving linear system of equations

$$Ax=b$$,

WHERE $A_{nxn}$ is a symetric positive define matrix. This problem can equivalent to the minimization problem:

$$min \ \phi(x) := \frac{1}{2} x^{T}Ax-b^{T}x$$,

The gradient of $\phi$ equals the residual of the linear system,

$$\nabla \ \phi(x) = Ax -b := r(x)$$

in particular at $x=x_{k}$ we have

$$r_{k} = Ax_{k}-b$$


## CONJUGATED DIRECTION METHODS

$$P_{i}^{T} A p_{j} = 0,  for  \ all \   i \neq j$$

Given a starting point $x_{0} \in \mathbb{R}^{n}$ and a set of conjufated directions $\{ p_{0},p_{1},...,p_{n-1}\}$ que can generate the sequence $\{x_{k}\}$


$$x_{k+1} = x_{k} + \alpha_{k}p_{k}$$

Where

$$\alpha_{k} = - \frac{r_{k}^{T}p_{k}}{p_{k}^{t}Ap_{K}} $$


#### Theorem

_For any $x_{0} \in \mathbb{R}^{n}$ the sequence $\{x_{k}\}$ generated be the conjugated direction algorithm, converges to the solution $x^{*}$ of the linear system in at most $n$ steps._



When $A$ is diagonal qe can trsnform the prolem to minimize along the coordinate direction. We define a new variable $\hat{x}$

$$\hat{x} = S^{-1}x$$

Where $S$ is the $nxn$ matrix defined be

$$S = \left[ p_{0}\  p_{1} ... p_{n-1} \right] $$

where $\{ p_{0},p_{1},...,p_{n-1}\}$ is the set of conjugated directions with respect to $A$. The quadratic $\phi$ defined now becomes

$$\hat{\phi}(\hat{x}) : = \phi(S\hat{x}) = \frac{1}{2}\hat{x}^{T}(S^{T}AS)\hat{x}-(S^{T}b)^{T}\hat{x}$$



$$r_{k+1} = r_{k} + \alpha_{k}Ap_{k}$$



## BASIC PROPERTIES OF THE CONJUGATED GRADIENT METHOD

* we can compute a new vector $p_{k}$ by using only the previous vector $p_{k-1}$

$$p_{k} = -r_{k} + \beta_{k}\ p_{k-1}$$

$p_{k-1}^{T} Ap_{k} =0$

$$ \beta_{k} =\frac{r_{k}^{T}Ap_{k-1}}{p_{k}^{T}Ap_{k-1}}$$



## A PRACTICAL FORM OF THE CONJUGATE GRADIENT METHOD

$$\alpha_{k} = \frac{r_{k}^{T}r_{k}}{p_{k}^{T}Ap_{k}}$$

$$\beta_{k+1} = \frac{r_{k+1}^{T}r_{k+1}}{r_{k}^{T}r_{k}} $$

#### Algorithm

Given $x_{0}$;


Set $r_{0} \leftarrow Ax_{0}-b$, $p_{0} \leftarrow -r_{0}$, $k\leftarrow 0$;

while $r_{k} \neq 0$

$$\alpha_{k} \leftarrow \frac{r_{k}^{T}r_{k}}{p_{k}^{T}Ap_{k}} ;$$

$$x_{k+1} \leftarrow x_{k} + \alpha_{k} p_{k} ;$$

$$r_{k+1}\leftarrow r_{k}+\alpha_{k}Ap_{k};$$

$$\beta_{k+1} \leftarrow \frac{r_{k+1}^{T}r_{k+1}}{r_{k}^{T}r_{k}}$$

$$p_{k+1} \leftarrow -r_{k+1} + \beta_{k+1}p_{k};$$

$$k \leftarrow k+1;$$

end (while)

fuente: _Nocedal Jorge , Wright Stephen J., Numerical Optimization, Second Edition (2006) 101-133_

In [1]:
import numpy as np

In [2]:
a = np.array([[3, 2, -1], [2, -1, 1], [-1, 1, -1]])
b = np.array([1, -2, 0])
x = np.array([-2, 9,11])

In [3]:
np.dot(a,x)

array([ 1, -2,  0])

In [4]:
def cgm(A,b,x):
    """
    input:
            A: Coeficient matrix
            b: solution vector
            x: vector to be optimize
        output:
            x: optimiza vector
    """
    r = np.dot(A,x)-b
    p = -r
    k = 0
    #print(r)
    
    while True: 
    #np.linalg.norm(r) < 1e-8:
    #k <4:
    #np.linalg.norm(r) < 1e-16:
    
    #(r < 1e-17).all():
        r_s = np.dot(np.transpose(r),r)
        alpha_k = r_s/np.dot(np.transpose(p),np.dot(A,p))
        
        x = x + np.dot(alpha_k,p)
        
        r = r + np.dot(alpha_k, np.dot(A,p))
        
        beta = np.dot(np.transpose(r),r)/r_s
        
        p = -r + beta*p
        
        k = k+1
        #print(x)
        if np.linalg.norm(r) < 1e-10:
            break
        if k > 10:
            break
        #print(k)
    
    return x
    

In [5]:
cgm(a,b,np.array([1,2,3]))

array([-2.,  9., 11.])

In [6]:
np.linalg.solve(a, b)

array([-2.,  9., 11.])

In [7]:
x_sol = cgm(a,b,np.array([1,1,1]))

In [8]:
np.linalg.norm(np.linalg.solve(a, b)-x_sol)

9.820297636185407e-15